# See https://github.com/unitycatalog/unitycatalog/blob/main/compose.yaml for the full compose file.
name: unitycatalog

services:

  unitycatalog:
    image: unitycatalog/unitycatalog:main-3172b4c
    hostname: unitycatalog
    container_name: unitycatalog
    ports:
      - "8080:8080"
    volumes:
      - type: bind
        source: ./etc/conf/server.properties
        target: /home/unitycatalog/etc/conf/server.properties
      - type: bind
        source: ./data
        target: /home/unitycatalog/etc/data
      - type: bind
        source: ./scripts
        target: /scripts
    networks:
      - unity

  duckdb-playground:
    build:
      context: .
      dockerfile: Dockerfile
    image: duckdb-playground:latest
    hostname: duckdb-playground
    container_name: duckdb-playground
    volumes:
      - type: bind
        source: ./data
        target: /home/unitycatalog/etc/data
      - type: bind
        source: ./scripts
        target: /opt/workspace/scripts
    ports:
      - "2718:2718"
    networks:
      - unity

networks:
  unity:
    driver: bridge
